apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webdeployments.mydomain.local
spec:
  scope: Namespaced
  group: mydomain.local
  names:
    kind: WebDeployment
    plural: webdeployments
    singular: webdeployment
    shortNames:
      - wdts
      - wdt
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          priority: 0
          jsonPath: .spec.replicas
          description: Amount of replicas
        - name: Image
          type: string
          priority: 0
          jsonPath: .spec.image
          description: Container image (and tag)
        - name: Host
          type: string
          priority: 0
          jsonPath: .spec.host
          description: Host where the application is accessible
